TRAIN_BATCH_SIZE = 8
EPOCHS = 1000
LEARNING_RATE = 2e-5
PATIENCE = 20
DROPOUT = 0.5
HIDDEN_DROPOUT_PROB = 0.1
ATTENTION_PROBS_DROPOUT_PROBS = 0.2
ALGO = 'BERT'
FREEZE_BERT = True
HEAD_TYPE = 'MLP' #Options: 'MLP', 'GRU'
MULTIHEAD = False
BIODIRECTIONAL_GRU = True
GRU_HIDDEN_DIM = 20
MODEL_PATH = './../saved_model/model.pt'
MODEL_PATH_FOR_EVALUATION_ONLY = './../../saved_model_trained_one_by_one/saved_model_class_19/model.pt' #'./../../saved_model_trained_one_by_one/saved_model_w_multi_heads/model.pt'
MAX_LENGTH = 128 #If -1 it will be specified automatically based on the length of the sentence with the max number of words
LOSS = 'BCE' # 'BCE', 'sigmoidF1'
SINGLE_CLASS = True
CLASS = 19
W_LOSS_WEIGHTS = False
TRAIN = False